local customUIAssets = {
    -- Core Scenarios
    {name = "scenario-image-hon-core-cover", url = "https://drive.google.com/uc?export=download&id=1wcLB15HCiWPc8JbTj3ouFGahFIoEX87X"},
    {name = "scenario-image-hon-core-01", url = "https://drive.google.com/uc?export=download&id=1j2RxsKWDcTBXL4qELJDh5fw3LAA9G1nE"},
    {name = "scenario-image-hon-core-02", url = "https://drive.google.com/uc?export=download&id=10PDeFmgocUZJTX46zUKx6mJxCQCvdS09"},
    {name = "scenario-image-hon-core-03", url = "https://drive.google.com/uc?export=download&id=1JXU6Z4eL_AoLK8GgifhS-BCs3boXBOb7"},
    {name = "scenario-image-hon-core-04", url = "https://drive.google.com/uc?export=download&id=1mAmWdpOnZ_L2KSu16ugULLXtE0IFzy4F"},
    {name = "scenario-image-hon-core-05", url = "https://drive.google.com/uc?export=download&id=1YmjAuhL-Y41kknGNj89EZqI3PQVTrIy9"},
    {name = "scenario-image-hon-core-06", url = "https://drive.google.com/uc?export=download&id=1sQcriOVhMdVzc68gaxEFLzmQJlNqT5bB"},
    {name = "scenario-image-hon-core-07", url = "https://drive.google.com/uc?export=download&id=1wQUA55UkvHP35VnvG9jCQjcMdmYYWx7a"},
    {name = "scenario-image-hon-core-08", url = "https://drive.google.com/uc?export=download&id=1vSeHhc5ne6v8JNd2-nRmbL__UXVUDhmc"},
    {name = "scenario-image-hon-core-09", url = "https://drive.google.com/uc?export=download&id=1s25oJMIW8ypKq7jM5EJNDr2DJPiUVwj2"},
    {name = "scenario-image-hon-core-10", url = "https://drive.google.com/uc?export=download&id=1ZqIfxwVXqhCI9U_wZQfoBpRe5chq76KS"},

    -- Carentan Scenarios
    {name = "scenario-image-carentan-cover", url = "https://drive.google.com/uc?export=download&id=1KDsHDuaRspMneZjHWnDpbAC1lyiwS_NE"},
    {name = "scenario-image-carentan-01", url = "https://drive.google.com/uc?export=download&id=1leE_rndbSX51Yr5cxqEHyF7JG71HW_Px"},
    {name = "scenario-image-carentan-02", url = "https://drive.google.com/uc?export=download&id=1VtjSpsP5OV5b3U_N3vgfdeYFSW85f2aX"},
    {name = "scenario-image-carentan-03", url = "https://drive.google.com/uc?export=download&id=1wB1IP_tbNtbZBcYAiNoJFTkEej4x1BiJ"},
    {name = "scenario-image-carentan-04", url = "https://drive.google.com/uc?export=download&id=1A8gUU2PF8qH1qMxoGZh7CQw69ctM6IdO"},
    {name = "scenario-image-carentan-05", url = "https://drive.google.com/uc?export=download&id=1xSAxsK1btWzw0E27paiRkPDq4Il4tP1q"},
    {name = "scenario-image-carentan-06", url = "https://drive.google.com/uc?export=download&id=1Ia7VoNRvKrg_5fgoLdLhxmX8EMBuoNt0"},
}


function GetCustomUIAssets()
    return customUIAssets
end
