--[[
## Summary
Split a string into an array of strings by separating the string into substrings,
using a specified separator string to determine where to make each split.

By default uses whitespace as a separator.

## Source
https://stackoverflow.com/a/7615129
--]]
function SplitString(inputstr, sep)
    sep = sep or "%s"

    local t={}
    local i=1
    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
        t[i] = str
        i = i + 1
    end
    return t
end
