GUIDs = {
    ["demolition-charge-yellow"] = 'ptlfpz',
    ["demolition-charge-red"] = 'do412h',
    ["ruin-r5-b"] = 'kjf90c',
    ["ruin-r2-b"] = 'wl8cqb',
    ["ruin-r1-b"] = '32squo',
    ["destroyed-bridge-r4-b"] = 'wd98tk',
    ["destroyed-bridge-r2-b"] = 'kc8t9g',
    ["detonator-yellow"] = 'pz8owg',
    ["detonator-red"] = 'hlkhtp',
    ["originals"] = 'amdjmx',
    ["full-resolution"] = '7318px',
    ["lower-resolution-smaller-filesize-for-tts"] = 'hx1cqk',
}