--[[ All of the tests for the HeroesSystem package. ]]--

--[[ #include tests here. ]]
-- #include Expansions/HeroesOfNormandie/CoreBoxUnitTest
-- #include Expansions/HeroesOfNormandie/CoreBoxIntegrationTest
-- #include Expansions/HeroesOfNormandie/LayoutSimpleScenario
#include ScenarioElements/TestBattlefield

--[[ #include tools/adhoc here. ]]
-- #include Expansions/HeroesOfNormandie/TestAdhoc
-- #include Expansions/HeroesOfNormandie/CoreBoxSnapPoints
